set(ML_MODULE_LIB ml_gmm)
add_library(ml_gmm INTERFACE)
target_link_libraries(ml_gmm INTERFACE ml_core)
target_include_directories(ml_gmm INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
set(ML_MODULE_RESULTS ${CMAKE_CURRENT_SOURCE_DIR}/results)
add_lesson_executable(ugm_theory 01_theory.cpp)
add_lesson_executable(ugm_math_intuition 02_math_intuition.cpp)
add_lesson_executable(ugm_implementation 03_implementation.cpp)
add_lesson_executable(ugm_end_to_end 04_end_to_end.cpp)
add_lesson_executable(ugm_predict predict.cpp)
