set(ML_MODULE_LIB ml_local_outlier_factor)
add_library(ml_local_outlier_factor INTERFACE)
target_link_libraries(ml_local_outlier_factor INTERFACE ml_core)
target_include_directories(ml_local_outlier_factor INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
set(ML_MODULE_RESULTS ${CMAKE_CURRENT_SOURCE_DIR}/results)
add_lesson_executable(ulof_theory 01_theory.cpp)
add_lesson_executable(ulof_math_intuition 02_math_intuition.cpp)
add_lesson_executable(ulof_implementation 03_implementation.cpp)
add_lesson_executable(ulof_end_to_end 04_end_to_end.cpp)
add_lesson_executable(ulof_predict predict.cpp)
