set(ML_MODULE_LIB ml_one_class_svm)
add_library(ml_one_class_svm INTERFACE)
target_link_libraries(ml_one_class_svm INTERFACE ml_core)
target_include_directories(ml_one_class_svm INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
set(ML_MODULE_RESULTS ${CMAKE_CURRENT_SOURCE_DIR}/results)
add_lesson_executable(uocsvm_theory 01_theory.cpp)
add_lesson_executable(uocsvm_math_intuition 02_math_intuition.cpp)
add_lesson_executable(uocsvm_implementation 03_implementation.cpp)
add_lesson_executable(uocsvm_end_to_end 04_end_to_end.cpp)
add_lesson_executable(uocsvm_predict predict.cpp)
