set(ML_MODULE_LIB ml_isolation_forest)
add_library(ml_isolation_forest INTERFACE)
target_link_libraries(ml_isolation_forest INTERFACE ml_core)
target_include_directories(ml_isolation_forest INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
set(ML_MODULE_RESULTS ${CMAKE_CURRENT_SOURCE_DIR}/results)
add_lesson_executable(uif_theory 01_theory.cpp)
add_lesson_executable(uif_math_intuition 02_math_intuition.cpp)
add_lesson_executable(uif_implementation 03_implementation.cpp)
add_lesson_executable(uif_end_to_end 04_end_to_end.cpp)
add_lesson_executable(uif_predict predict.cpp)
