add_subdirectory(01_logistic_regression)
add_subdirectory(02_knn_classification)
add_subdirectory(03_svm_classification)
add_subdirectory(04_naive_bayes)
add_subdirectory(05_decision_tree_classifier)
add_subdirectory(06_random_forest_classifier)
add_subdirectory(07_adaboost_classifier)
add_subdirectory(08_gradient_boosting_classifier)
add_subdirectory(09_mlp_classifier)
add_subdirectory(10_model_evaluation)
add_subdirectory(11_lda)
add_subdirectory(12_qda)
add_subdirectory(13_imbalanced_classification)
