add_subdirectory(01_linear_regression)
add_subdirectory(02_knn_regression)
add_subdirectory(03_decision_tree_regressor)
add_subdirectory(04_random_forest_regressor)
add_subdirectory(05_gradient_boosting_regressor)
add_subdirectory(06_mlp_regressor)
add_subdirectory(07_elastic_net)
add_subdirectory(08_svr)
add_subdirectory(09_gaussian_process)
