set(ML_MODULE_LIB ml_tsne)
add_library(ml_tsne INTERFACE)
target_link_libraries(ml_tsne INTERFACE ml_core)
target_include_directories(ml_tsne INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
set(ML_MODULE_RESULTS ${CMAKE_CURRENT_SOURCE_DIR}/results)
add_lesson_executable(utsne_theory 01_theory.cpp)
add_lesson_executable(utsne_math_intuition 02_math_intuition.cpp)
add_lesson_executable(utsne_implementation 03_implementation.cpp)
add_lesson_executable(utsne_end_to_end 04_end_to_end.cpp)
